### ISSUE TITLE
Pad placeholder does not dissapear after new line entered

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#260]
![captura de pantalla de 2016-05-09 12 18 19](https://cloud.githubusercontent.com/assets/7475584/15110366/bc5e5d04-15e0-11e6-87e0-e67efd5baa7e.png)

**Comment by llopv** [comment]
LOL

**Comment by atd** [comment]
https://github.com/P2Pvalue/angular-swellrt/blob/master/angular-swellrt.js#L711

**Comment by llopv** [comment]
You can add placeholders to contenteditable elements using only CSS, maybe `.swellrt-placeholder` element isn't needed.

```css
.swellrt-editor [contenteditable=true]:empty:before {
  content: attr(placeholder);
  display: block; /* For Firefox */
}
```
From http://codepen.io/flesler/pen/AEIFc
